### ISSUE TITLE
[question] PHP minimum version

### ISSUE THREAD

**Issue by jmleroux** [worldia/textmaster-api#20]
Hello @cdaguerre ,

Why did you choose PHP 5.3 as minimum version ?
Even Debian stable install a PHP 5.4, wich is already quite old.

Regards,
JM

**Comment by cdaguerre** [comment]
Hi @jmleroux 
We aligned the minimum requirement on those of the guzzle library we use.
For now, we haven't had any need to increase the requirement, apart from some syntax drawbacks which are easy to circumvent... 
(like short array syntax or traits)

**Comment by jmleroux** [comment]
OK no problem for me.
Thanks for the quick answer.
