### ISSUE TITLE
Project language code is only 2 characters in API call

### ISSUE THREAD

**Issue by Pitoune** [worldia/textmaster-api#59]
@aponsin
When I do a call API to retrieve a Project the language code is only 2 characters. 
How can I know if the language is `en-us` or `en-gb` ?

**Comment by aponsin** [comment]
Can you provide the project id you are referencing to ?

**Comment by Pitoune** [comment]
Sure:
id: 573acf6c955957384d66fbfe
name: Projet de type "product" du "17/05/2016"
reference: TR-23A-70827

**Comment by aponsin** [comment]
Ok, this is a bug on us.
For compatibility reason we do expose the language code as the very old 2 letter version we used too in the past. We can't break that backward compatibility.
I'll discuss with my API engineer tomorrow and get back to you with a solution (most likely adding a new field to expose those missing information).

**Comment by Pitoune** [comment]
OK thanks !

**Comment by aponsin** [comment]
Ok you should now be able to use the following fields names instead:

- :language_from_code
- :language_to_code

We'll deprecated the other ones and update the documentation.

**Comment by Pitoune** [comment]
It works !
Thanks a lot
