### ISSUE TITLE
Document status on a "complete document" API call

### ISSUE THREAD

**Issue by Pitoune** [worldia/textmaster-api#66]
According to documentation and the tests I have made, the document status returned by an API call to "complete document" is ìn_review`. 
According to the workflow I would expect status `completed`. Is there any chance you change it ?

**Comment by aponsin** [comment]
I am not sure what you mean ?
When a document is completed, his status should definitely be "completed".

**Comment by Pitoune** [comment]
I agree. But the API response is returning "in_review".
As it is documented here https://fr.app.sandbox.textmaster.com/api-documentation#documents-complete-document

**Comment by aponsin** [comment]
Ok. I looked into this. So indeed, you are right, we'll return the status as "in_review", the reason being that the action that is happening is actually asynchronous on that end point. Meaning that by the time we respond, the completion as not actually happened. If you want to catch the completion of that event, you should set a callback on it.
Sorry, it was definitely not clear from the documentation.

**Comment by Pitoune** [comment]
Thanks. It is clear now.
