### ISSUE TITLE
Method filter in ProjectApi does not work

### ISSUE THREAD

**Issue by Pitoune** [worldia/textmaster-api#7]

**Comment by Pitoune** [comment]
I reopen the issue because the 3 projects which are not in a usable state are still returned by the API.
This is no big deal for us. But you told us it should be cleaned out automatically and it is not.

**Comment by Pitoune** [comment]
@aponsin we need your help on this

**Comment by aponsin** [comment]
Indeed. Just realized that that cron to clean-up temporary projects is not activated on staging. I have cleaned them manually. You should be good now.

**Comment by Pitoune** [comment]
Yes !
Thanks a lot !
