### ISSUE TITLE
ResponseMediator does not always throw exceptions

### ISSUE THREAD

**Issue by jmleroux** [worldia/textmaster-api#72]
For some Textmaster responses, the ResponseMediator does not throw exception because the error message is not in the first level of the retruned array.
Example :
[This method](https://github.com/worldia/textmaster-api/blob/master/lib/Textmaster/Api/Project/Document.php#L196) will return an array where the error is not at first level, so the ResponseMediator will not see it.

Here is the code to thorw an exception :
https://github.com/worldia/textmaster-api/blob/master/lib/Textmaster/HttpClient/Message/ResponseMediator.php#L33

Shouldn't it be better to also parse the response HTTP_CODE to detect errors ?

Regards,
JM

**Comment by cdaguerre** [comment]
You're right, http status code should be checked as well. Could you make a PR?

**Comment by jmleroux** [comment]
I don't have much time right now. If i find some time, i will.
