### ISSUE TITLE
AbstractObject::getProperty() should be public

### ISSUE THREAD

**Issue by jmleroux** [worldia/textmaster-api#73]
I need to access the `updated_at` property of a Document response, but there is no getter to acces it from a Document object.
I think the `getProperty` should be public to let developpers access any document property. Plus, if the Document response change, devs will be able to access new properties.

The alternative could be to make a getter for each and every property.

Regards,
JM

**Comment by cdaguerre** [comment]
We would rather stick to concrete getters and setters. Could you make a PR for the updateAt property?

**Comment by jmleroux** [comment]
done ;)
