### ISSUE TITLE
[Question] Functionnal test create too much projects

### ISSUE THREAD

**Issue by jmleroux** [worldia/textmaster-api#78]
Hello,

I don't know if it is a real issue, but when i query the sandbox projects (`http://api.sandbox.textmaster.com/v1/clients/projects`), i get something like 123 pages of projects.
Do you plan to purge them at some time ?

Regards,
JM

**Comment by aponsin** [comment]
I wasn't planning on it, but if they are bothering you I definitely can.

**Comment by jmleroux** [comment]
No it's not a problem, just a question. The fact is that the functionnal tests create and cancel dummy projects, but when these tests fail, the projects can remain. Not a problem for me, i was just wondering about data volume.
